---
  # Play1 - WebServer related tasks
  - name: Play Web - Create apache directories and username in web servers
    hosts: webservers
    become: yes
    become_user: root
    tasks:
      #  - name: create username apacheadm
      # user:
      #   name: apacheadm
      #   group: users,admin
      #   shell: /bin/bash
      #   home: /home/weblogic

      - name: install apache httpd
        apt:
          name: apache2
          state: present
